import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header'
import BottomHeader from "@/components/BottomHeader";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout/Layout";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-bodyFont`}
      >
        <Layout>
          <div className="sticky top-0 z-10 bg-white">
            <Header />
            <BottomHeader />
          </div>
          {children}
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
